basePath: /api/v1
definitions:
  internal_server.AccountLoginRequest:
    properties:
      email:
        example: john.doe@example.com
        type: string
      password:
        example: password123{#Pbb
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  internal_server.DropEggRequest:
    properties:
      lat:
        type: number
      lon:
        type: number
      message:
        type: string
      player_id:
        type: string
      type:
        enum:
        - BUNNY
        - GOLDEN
        - LEGENDARY
        type: string
    required:
    - lat
    - lon
    - player_id
    - type
    type: object
  internal_server.DropEggResponse:
    properties:
      created_at:
        type: string
      inventory_id:
        type: string
      lat:
        type: number
      lon:
        type: number
      message:
        type: string
      type:
        type: string
    type: object
  internal_server.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: string
    type: object
  internal_server.GetEggsByPlayerResponse:
    properties:
      collected_at:
        type: string
      hatched:
        type: boolean
      inventory_id:
        type: string
      message:
        type: string
      type:
        type: string
    type: object
  internal_server.GetToolsByPlayerResponse:
    properties:
      description:
        type: string
      durability:
        type: integer
      equipped:
        type: boolean
      inventory_id:
        type: string
    type: object
  internal_server.Inventory:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      item_type:
        type: string
      player_id:
        type: string
      quantity:
        type: integer
    type: object
  internal_server.Message:
    properties:
      code:
        example: 500
        type: integer
      error:
        example: Failed to Process Task
        type: string
      message:
        example: Task status updated - COMPLETED
        type: string
      result:
        example: Task processed successfully
        type: string
      task_id:
        example: 1233-flf4djf-alsdik
        type: string
    type: object
  internal_server.Players:
    properties:
      account_id:
        type: string
      coins:
        type: integer
      created_at:
        type: string
      id:
        type: string
      level:
        type: integer
      settings:
        items:
          type: integer
        type: array
      updated_at:
        type: string
      xp:
        type: integer
    type: object
  internal_server.RegisterAccountRequest:
    properties:
      email:
        example: john.doe@example.com
        type: string
      first_name:
        example: John
        type: string
      last_name:
        example: Doe
        type: string
      password:
        example: password123{#Pbb
        minLength: 8
        type: string
      username:
        example: John_doe11
        maxLength: 30
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
  internal_server.renewAccessTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  internal_server.renewAccessTokenResponse:
    properties:
      access_token:
        type: string
      access_token_expires_at:
        type: string
    type: object
info:
  contact: {}
  description: API documentation for the eggsplore game
  title: Eggsplore API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login account with email and password
      parameters:
      - description: Account Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_server.AccountLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Login Account
      tags:
      - auth
  /auth/logout:
    post:
      description: Logout account by deleting session and clearing cookies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.Message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Logout Account
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register account with email and password
      parameters:
      - description: Account Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_server.RegisterAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Register Account
      tags:
      - auth
  /auth/renew:
    post:
      consumes:
      - application/json
      description: Generates a new access token using a valid refresh token
      parameters:
      - description: Refresh Token Request
        in: body
        name: body
        schema:
          $ref: '#/definitions/internal_server.renewAccessTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.renewAccessTokenResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "401":
          description: Unauthorized or Invalid token
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "404":
          description: Session not found
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Renew Access Token
      tags:
      - auth
  /game/eggs:
    get:
      description: Get all eggs belonging to a player
      parameters:
      - description: Player ID
        in: query
        name: player_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_server.GetEggsByPlayerResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Get Player Eggs
      tags:
      - game
    post:
      consumes:
      - application/json
      description: Player drops an egg (adds to inventory + eggs table)
      parameters:
      - description: Drop Egg Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_server.DropEggRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.DropEggResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Drop Egg
      tags:
      - game
  /game/inventory:
    get:
      description: Get all inventory items (tools, eggs, boosts) belonging to a player
      parameters:
      - description: Player ID
        in: query
        name: player_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_server.Inventory'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Get Player Inventory
      tags:
      - game
  /game/player:
    get:
      description: Get player stats by account id
      parameters:
      - description: Account ID
        in: query
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.Players'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Get Player Stats
      tags:
      - game
  /game/tools:
    get:
      description: Get all tools belonging to a player
      parameters:
      - description: Player ID
        in: query
        name: player_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_server.GetToolsByPlayerResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Get Player Tools
      tags:
      - game
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
