// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Accounts struct {
	ID           uuid.UUID   `json:"id"`
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	Username     pgtype.Text `json:"username"`
	Email        string      `json:"email"`
	Password     string      `json:"password"`
	ProfileUrl   pgtype.Text `json:"profile_url"`
	Status       string      `json:"status"`
	Role         string      `json:"role"`
	Is2faEnabled pgtype.Bool `json:"is_2fa_enabled"`
	OtpCode      pgtype.Text `json:"otp_code"`
	OtpExpiresAt pgtype.Text `json:"otp_expires_at"`
	IsApproved   bool        `json:"is_approved"`
	IsVerified   bool        `json:"is_verified"`
	CreatedAt    time.Time   `json:"created_at"`
	LastActive   time.Time   `json:"last_active"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	AccountID    uuid.UUID `json:"account_id"`
	RefreshToken string    `json:"refresh_token"`
	AccountAgent string    `json:"account_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}
